server:
  port: 9600
spring:
  application:
    name: dynamic-route-service
  # dev环境
  profiles:
    active: dev
  thymeleaf:
    cache: false
    mode: HTML
  # 数据源
  redis:
    host: 127.0.0.1
    port: 6379
#    password: YiZheng123456
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gateway?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 1800000
      idle-timeout: 30000
      auto-commit: true
      pool-name: PbHikariCP
      connection-test-query: SELECT 1
      connection-timeout: 30000

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zypcy.springcloud.dynamicroute.entity


# 注册中心
eureka:
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
